USE umDb
GO

INSERT INTO cls_estados (Nombre_Estado, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador,Id_Transaccion, Activo) VALUES
('ACTIVO',GETDATE(),GETDATE(),NULL,NULL,NULL,1), 
('INACTIVO',GETDATE(),GETDATE(),NULL,NULL,NULL,1), 
('PENDIENTE',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
('EN REVISION',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
('APROBADA', GETDATE(),GETDATE(),NULL,NULL,NULL,1),
('RECHAZADA', GETDATE(), GETDATE(),NULL,NULL,NULL,1),
('PLANIFICADA', GETDATE(), GETDATE(),NULL,NULL,NULL,1);

INSERT INTO cls_tipos_catalogos  (Nombre_Tipo_Catalogo, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador,Id_Transaccion, Activo) VALUES 
('TIPO DOCUMENTO' , GETDATE(), GETDATE(), NULL,NULL,NULL,1),   --1
('GENERO PERSONA' , GETDATE(), GETDATE(), NULL,NULL,NULL,1),   --2
('NACIONALIDAD' , GETDATE(), GETDATE(), NULL,NULL,NULL,1),	   --3
('ESTADO CIVIL' , GETDATE(), GETDATE(), NULL,NULL,NULL,1),	   --4
('TIPO PROGRAMA', GETDATE(), GETDATE(), NULL, NULL,NULL,1),	   --5
('TIPO SANCION', GETDATE(), GETDATE(), NULL, NULL,NULL,1),	   --6
('TIPO SEVERIDAD', GETDATE(), GETDATE(),NULL,NULL,NULL,1),	   --7
('TIPO EVALUACION', GETDATE(), GETDATE(),NULL,NULL,NULL,1); --8


INSERT INTO cls_tipos_catalogos  (Nombre_Tipo_Catalogo, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador,Id_Transaccion, Activo) VALUES 
('TIPO CONTACTO', GETDATE(), GETDATE(), NULL, NULL,NULL,1); -- 9

INSERT INTO cls_catalogos (Id_Tipo_Catalogo, Nombre_Catalogo, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador,Id_Transaccion, Activo) VALUES
(1, 'CEDULA NICARAGUENSE', GETDATE(), GETDATE(), NULL, NULL,NULL,1),  
(2, 'MASCULINO', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(2, 'FEMENINO', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(2, 'OTRO', GETDATE(),GETDATE(),NULL,NULL,NULL,1),
(2,'PREFIERO NO DECIRLO',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
(3, 'NICARAGUENSE', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(3, 'COSTARRICENSE', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(4, 'SOLTERO/A', GETDATE(), GETDATE(), NULL, NULL,NULL, 1),
(4, 'CASADO/A', GETDATE(), GETDATE(), NULL, NULL,NULL, 1),
(4, 'VIUDO/A', GETDATE(), GETDATE(), NULL, NULL,NULL, 1),
(4, 'DIVORCIADO/A', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(4, 'SEPARADO/A', GETDATE(), GETDATE(), NULL, NULL,NULL, 1),
(4, 'UNION CIVIL', GETDATE(), GETDATE(), NULL, NULL,NULL, 1),
(5, 'BECA', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(5, 'MAESTRIA', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(5, 'POSGRADO', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(6, 'PLAGIO', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(6, 'COPIA EN EXAMEN', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(6, 'SUPLANTACION', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(6, 'INASISTENCIAS',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
(6, 'ACOSO',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
(6, 'VIOLENCIA',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
(6, 'USO INDEBIDO DE SISTEMAS',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
(6, 'SABOTAJE TI',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
(7, 'LEVE', GETDATE(), GETDATE(),NULL,NULL,NULL,1),
(7, 'GRAVE', GETDATE(), GETDATE(),NULL,NULL,NULL,1),
(7, 'MUY GRAVE', GETDATE(), GETDATE(),NULL,NULL,NULL,1),
(8, 'ESCRITA', GETDATE(), GETDATE(),NULL,NULL,NULL,1),
(8, 'SELECCION MULTIPLE', GETDATE(), GETDATE(),NULL,NULL,NULL,1),
(8, 'DEFENSA', GETDATE(), GETDATE(),NULL,NULL,NULL,1),
(8, 'CALIFICACION EN LINEA',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
(8, 'MERITO DOCENTE',GETDATE(),GETDATE(),NULL,NULL,NULL,1);

INSERT INTO cls_catalogos (Id_Tipo_Catalogo, Nombre_Catalogo, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador,Id_Transaccion, Activo) VALUES
(9, 'CORREO ELECTRONICO', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(9, 'TELEFONO MOVIL', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(9, 'TELEFONO FIJO', GETDATE(), GETDATE(), NULL, NULL,NULL,1);


INSERT INTO cls_roles (Nombre_Rol, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador,Id_Transaccion,Activo) VALUES
('ADMINISTRADOR', GETDATE(), GETDATE(), 1, 1, NULL, 1),
('DOCENTE', GETDATE(), GETDATE(), 1, 1, NULL, 1),
('ALUMNO', GETDATE(), GETDATE(), 1, 1, NULL, 1),
('AUDITOR', GETDATE(), GETDATE(), 1, 1, NULL, 1),
('COORDINADOR ACADEMICO', GETDATE(), GETDATE(), 1, 1, NULL, 1),
('GESTOR BECAS', GETDATE(), GETDATE(), 1, 1, NULL, 1);


INSERT INTO cls_menus(Menu, Fecha_Creacion,Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo)VALUES 
('USUARIOS',GETDATE(),GETDATE(),1,1,NULL,1),		-- 1
('MIS EVALUACIONES',GETDATE(),GETDATE(),1,1,NULL,1), -- 2
('MIS MATERIAS',GETDATE(),GETDATE(),1,1,NULL,1),-- 3
('CONVOCATORIAS',GETDATE(),GETDATE(),1,1,NULL,1), -- 4
('MIS SECCIONES',GETDATE(),GETDATE(),1,1,NULL,1), -- 5
('HISTORIAL',GETDATE(),GETDATE(),1,1,NULL,1),-- 6
('CONFIGURACIONES SISTEMA', GETDATE(), GETDATE(),1,1,NULL,1),  -- 7
('GESTIONAR BECAS', GETDATE(), GETDATE(),1,1,NULL,1); -- 8

INSERT INTO cls_menus_roles(Id_Menu, Id_Rol,Fecha_Creacion,Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo) VALUES
(1,1,GETDATE(),GETDATE(),1,1,NULL,1),
(2,3,GETDATE(),GETDATE(),1,1,NULL,1),
(3,3,GETDATE(),GETDATE(),1,1,NULL,1),
(4,3,GETDATE(),GETDATE(),1,1,NULL,1),
(5,4,GETDATE(),GETDATE(),1,1,NULL,1),
(6,1,GETDATE(),GETDATE(),1,1,NULL,1),
(7,1,GETDATE(),GETDATE(),1,1,NULL,1),
(6,4,GETDATE(),GETDATE(),1,1,NULL,1),
(8,6,GETDATE(),GETDATE(),1,1,NULL,1);
