<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UmProject.Data\UmProject.Data.csproj" />
    <ProjectReference Include="..\UmProject.Entities\UmProject.Entities.csproj" />
  </ItemGroup>

</Project>
