USE umDb
GO


INSERT INTO cls_estados (Nombre_Estado, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador,Id_Transaccion, Activo) VALUES
('ACTIVO',GETDATE(),GETDATE(),NULL,NULL,NULL,1), 
('INACTIVO',GETDATE(),GETDATE(),NULL,NULL,NULL,1), 
('PENDIENTE',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
('EN REVISION',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
('APROBADA', GETDATE(),GETDATE(),NULL,NULL,NULL,1),
('RECHAZADA', GETDATE(), GETDATE(),NULL,NULL,NULL,1),
('PLANIFICADA', GETDATE(), GETDATE(),NULL,NULL,NULL,1);

INSERT INTO cls_tipos_catalogos  (Nombre_Tipo_Catalogo, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador,Id_Transaccion, Activo) VALUES 
('TIPO DOCUMENTO' , GETDATE(), GETDATE(), NULL,NULL,NULL,1),   --1
('GENERO PERSONA' , GETDATE(), GETDATE(), NULL,NULL,NULL,1),   --2
('NACIONALIDAD' , GETDATE(), GETDATE(), NULL,NULL,NULL,1),	   --3
('ESTADO CIVIL' , GETDATE(), GETDATE(), NULL,NULL,NULL,1),	   --4
('TIPO PROGRAMA', GETDATE(), GETDATE(), NULL, NULL,NULL,1),	   --5
('TIPO SANCION', GETDATE(), GETDATE(), NULL, NULL,NULL,1),	   --6
('TIPO SEVERIDAD', GETDATE(), GETDATE(),NULL,NULL,NULL,1),	   --7
('TIPO EVALUACION', GETDATE(), GETDATE(),NULL,NULL,NULL,1); --8


INSERT INTO cls_tipos_catalogos  (Nombre_Tipo_Catalogo, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador,Id_Transaccion, Activo) VALUES 
('TIPO CONTACTO', GETDATE(), GETDATE(), NULL, NULL,NULL,1); -- 9

INSERT INTO cls_catalogos (Id_Tipo_Catalogo, Nombre_Catalogo, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador,Id_Transaccion, Activo) VALUES
(1, 'CEDULA NICARAGUENSE', GETDATE(), GETDATE(), NULL, NULL,NULL,1),  
(2, 'MASCULINO', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(2, 'FEMENINO', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(2, 'OTRO', GETDATE(),GETDATE(),NULL,NULL,NULL,1),
(2,'PREFIERO NO DECIRLO',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
(3, 'NICARAGUENSE', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(3, 'COSTARRICENSE', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(4, 'SOLTERO/A', GETDATE(), GETDATE(), NULL, NULL,NULL, 1),
(4, 'CASADO/A', GETDATE(), GETDATE(), NULL, NULL,NULL, 1),
(4, 'VIUDO/A', GETDATE(), GETDATE(), NULL, NULL,NULL, 1),
(4, 'DIVORCIADO/A', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(4, 'SEPARADO/A', GETDATE(), GETDATE(), NULL, NULL,NULL, 1),
(4, 'UNION CIVIL', GETDATE(), GETDATE(), NULL, NULL,NULL, 1),
(5, 'BECA', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(5, 'MAESTRIA', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(5, 'POSGRADO', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(6, 'PLAGIO', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(6, 'COPIA EN EXAMEN', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(6, 'SUPLANTACION', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(6, 'INASISTENCIAS',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
(6, 'ACOSO',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
(6, 'VIOLENCIA',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
(6, 'USO INDEBIDO DE SISTEMAS',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
(6, 'SABOTAJE TI',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
(7, 'LEVE', GETDATE(), GETDATE(),NULL,NULL,NULL,1),
(7, 'GRAVE', GETDATE(), GETDATE(),NULL,NULL,NULL,1),
(7, 'MUY GRAVE', GETDATE(), GETDATE(),NULL,NULL,NULL,1),
(8, 'ESCRITA', GETDATE(), GETDATE(),NULL,NULL,NULL,1),
(8, 'SELECCION MULTIPLE', GETDATE(), GETDATE(),NULL,NULL,NULL,1),
(8, 'DEFENSA', GETDATE(), GETDATE(),NULL,NULL,NULL,1),
(8, 'CALIFICACION EN LINEA',GETDATE(),GETDATE(),NULL,NULL,NULL,1),
(8, 'MERITO DOCENTE',GETDATE(),GETDATE(),NULL,NULL,NULL,1);

INSERT INTO cls_catalogos (Id_Tipo_Catalogo, Nombre_Catalogo, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador,Id_Transaccion, Activo) VALUES
(9, 'CORREO ELECTRONICO', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(9, 'TELEFONO MOVIL', GETDATE(), GETDATE(), NULL, NULL,NULL,1),
(9, 'TELEFONO FIJO', GETDATE(), GETDATE(), NULL, NULL,NULL,1);

INSERT INTO tbl_personas(Primer_Nombre,Segundo_Nombre,Primer_Apellido,Segundo_Apellido,Fecha_Nacimiento,Id_Tipo_Documento,Valor_Documento,Id_Genero_Persona,Id_Nacionalidad,Id_Estado_Civil,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Id_Estado)
VALUES ('JUSTIN','ZAHIR','CALDERON','JOYA','2004-08-14',1,'0011408041050U',2,6,8,GETDATE(),GETDATE(),NULL,NULL,NULL,1)

INSERT INTO tbl_usuarios (Usuario,Contrasena,Fecha_Creacion,Fecha_Modificacion,Ultima_Sesion,Ultimo_Cambio_Contrasena,Id_Creador,Id_Modificador,Id_Transaccion,Id_Estado)
VALUES ('znr','$2a$11$lrqmyt.z2dgs1mnBp8InyuT.XJvS49jlTN.iPbGi.VYVlYYfWl22W',GETDATE(),GETDATE(),NULL,NULL,NULL,NULL,NULL,1)

-- ----------------------------------------------------------------
-- INSERTS MASIVOS: tbl_personas + tbl_usuarios (10 registros)
-- ----------------------------------------------------------------

/* PERSONAS */
INSERT INTO tbl_personas
(Primer_Nombre, Segundo_Nombre, Primer_Apellido, Segundo_Apellido, Fecha_Nacimiento,
 Id_Tipo_Documento, Valor_Documento, Id_Genero_Persona, Id_Nacionalidad, Id_Estado_Civil,
 Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Id_Estado)
VALUES
('MARIA',    'ELENA',  'LOPEZ',     'GARCIA',    '1990-03-22', 1, 'MLOP9003220001', 1, 6, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
('CARLOS',   'EDUARDO','RUIZ',      'MARTINEZ',  '1985-11-11', 1, 'CRUI8511110002', 2, 6, 2, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
('ANA',      'ISABEL', 'GOMEZ',     'PEREZ',     '1995-06-05', 1, 'AGOM9506050003', 1, 6, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
('LUIS',     'FERNANDO','HERRERA',   'SANCHEZ',   '1988-01-30', 1, 'LHERR8801300004', 2, 6, 3, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
('SOFIA',    'MAR',    'MARTINEZ',  'LOZANO',    '1992-09-09', 1, 'SMART9209090005', 1, 6, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
('DIEGO',    'ANDRES', 'ALVAREZ',   'TORRES',    '1979-12-01', 1, 'DALV7912010006', 2, 6, 2, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
('PAULA',    'ROCIO',  'CASTILLO',  'VARGAS',    '1998-07-17', 1, 'PCAST9807170007', 1, 6, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
('ROBERTO',  'MIGUEL', 'FERNANDEZ', 'OLIVARES',  '1982-04-24', 1, 'RFER8204240008', 2, 6, 2, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
('ELENA',    'MARIA',  'RIVERA',    'DOMINGUEZ', '1997-02-02', 1, 'ERIV9702020009', 1, 6, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1);

-- Nota: ajusta Id_Tipo_Documento, Id_Genero_Persona, Id_Nacionalidad, Id_Estado_Civil seg�n tu cat�logo real.
-- ----------------------------------------------------------------

/* USUARIOS (relacionados por Valor_Documento -> Id_Persona obtenido mediante subquery) 
   Las contrase�as est�n como hashes BCrypt (VARCHAR(100) ok). */

INSERT INTO tbl_usuarios
(Id_Persona, Usuario, Contrasena,
 Fecha_Creacion, Fecha_Modificacion, Ultima_Sesion, Ultimo_Cambio_Contrasena,
 Id_Creador, Id_Modificador, Id_Transaccion, Id_Estado)
VALUES
(
 (SELECT TOP 1 Id_Persona FROM tbl_personas WHERE Valor_Documento = 'MLOP9003220001'),
 'mlopez',
 '$2a$11$yF1h7KQ0Z8uQh6mYv1Pq9uk6dQ8b1aZ2xgEo2h2pQwX9ZJk4uT1e',
 GETDATE(), GETDATE(), NULL, NULL, NULL, NULL, NULL, 1
),
(
 (SELECT TOP 1 Id_Persona FROM tbl_personas WHERE Valor_Documento = 'CRUI8511110002'),
 'cruiz',
 '$2a$11$N8q5dYk3rPz7sT1vM2wXyue6ZfH0b9cQpLk3j2QfR8uVYc5tB0sG',
 GETDATE(), GETDATE(), NULL, NULL, NULL, NULL, NULL, 1
),
(
 (SELECT TOP 1 Id_Persona FROM tbl_personas WHERE Valor_Documento = 'AGOM9506050003'),
 'agomez',
 '$2a$11$Gz7wYb9Lp4Qk3sT1uV8nZeJ2yH5pM0qRrT6cXl8dF3sW1vN9bU0x',
 GETDATE(), GETDATE(), NULL, NULL, NULL, NULL, NULL, 1
),
(
 (SELECT TOP 1 Id_Persona FROM tbl_personas WHERE Valor_Documento = 'LHERR8801300004'),
 'lherrera',
 '$2a$11$Hk4pTz2Wq8Nn5cV7bJ1rYeL3oM9fG6sXcZ2vQw8yU5tR1pO0nB3d',
 GETDATE(), GETDATE(), NULL, NULL, NULL, NULL, NULL, 1
),
(
 (SELECT TOP 1 Id_Persona FROM tbl_personas WHERE Valor_Documento = 'SMART9209090005'),
 'smartinez',
 '$2a$11$Sx9kQw7Lm2Vc8bY1nZ4pEuF6hR3oJ0tWqY5zN8vC2mT1sP6aB7dE',
 GETDATE(), GETDATE(), NULL, NULL, NULL, NULL, NULL, 1
),
(
 (SELECT TOP 1 Id_Persona FROM tbl_personas WHERE Valor_Documento = 'DALV7912010006'),
 'dalvarez',
 '$2a$11$Vz2bQp5Lm8Wc1nR9sT3yEeF4uH7oK6jXzY1qP8vC2mT9sL4oN0gH',
 GETDATE(), GETDATE(), NULL, NULL, NULL, NULL, NULL, 1
),
(
 (SELECT TOP 1 Id_Persona FROM tbl_personas WHERE Valor_Documento = 'PCAST9807170007'),
 'pcastillo',
 '$2a$11$Qw3eRt6Yu9Ii2oP8Lm5VbN7cRf4tG1yHjK0oP8zX2cV7nM5sL1dB',
 GETDATE(), GETDATE(), NULL, NULL, NULL, NULL, NULL, 1
),
(
 (SELECT TOP 1 Id_Persona FROM tbl_personas WHERE Valor_Documento = 'RFER8204240008'),
 'rfernandez',
 '$2a$11$Lp6mNz1Qv8Xs3wT9bR4yCeF2oH5pK7jXzN1qP9vC3tS6uO2gH0dB',
 GETDATE(), GETDATE(), NULL, NULL, NULL, NULL, NULL, 1
),
(
 (SELECT TOP 1 Id_Persona FROM tbl_personas WHERE Valor_Documento = 'ERIV9702020009'),
 'erivera',
 '$2a$11$Tz8vWr2Yn6Qs4pHjM0lBeK9cX5oF1uG3rV7nP2wQ8sM6tL9kA4dB',
 GETDATE(), GETDATE(), NULL, NULL, NULL, NULL, NULL, 1
);





INSERT INTO cls_roles (Nombre_Rol, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador,Id_Transaccion,Activo) VALUES
('ADMINISTRADOR', GETDATE(), GETDATE(), 1, 1, NULL, 1);
INSERT INTO cls_usuarios_roles(Id_Usuario,Id_Rol,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo)
VALUES (1,1,GETDATE(),GETDATE(),1,1,NULL,1)



INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR ESTADOS', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('ACTUALIZAR ESTADOS', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('FILTRAR ESTADOS ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('FILTRAR ESTADOS POR TIPO TRANSACCION', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('LISTAR ULTIMOS 10 ESTADOS', GETDATE(), GETDATE(), NULL,NULL,NULL,1);

INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR TIPOS CATALOGOS', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('ACTUALIZAR TIPOS CATALOGOS', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('FILTRAR TIPOS DE CATALOGOS POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('LISTAR ULTIMOS 10 TIPOS DE CATALOGOS', GETDATE(), GETDATE(), NULL,NULL,NULL,1);

INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR CATALOGOS', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('ACTUALIZAR  CATALOGOS', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('FILTRAR CATALOGOS POR TIPO', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('FILTRAR CATALOGO ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('LISTAR ULTIMOS 10 CATALOGOS', GETDATE(), GETDATE(), NULL,NULL,NULL,1);

INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR PERSONAS', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('ACTUALIZAR  PERSONAS', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('FILTRAR PERSONAS POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('FILTRAR PERSONAS POR NUMERO DOCUMENTO', GETDATE(), GETDATE(), NULL,NULL,NULL,1); 

INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('INICIAR SESION', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 19
('AGREGAR USUARIOS', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('ACTUALIZAR USUARIOS', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('LISTAR USUARIOS', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('FILTRAR USUARIOS POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('FILTRAR USUARIOS POR USUARIO', GETDATE(),GETDATE(),NULL,NULL,NULL,1),
('FILTRAR USUARIOS POR ID PERSONA', GETDATE(),GETDATE(),NULL,NULL,NULL,1),
('LISTAR MENU POR ROL DE USUARIO', GETDATE(),GETDATE(),NULL,NULL,NULL,1);

INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR CONTACTO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 27
('ACTUALIZAR CONTACTO', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('FILTRAR CONTACTO POR PERSONA', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('FILTRAR CONTACTO POR ID CONTACTO', GETDATE(), GETDATE(), NULL,NULL,NULL,1);

INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR ROL', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 31
('ACTUALIZAR ROL', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('FILTRAR ROL POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('LISTAR ULTIMOS 10 ROLES', GETDATE(), GETDATE(), NULL,NULL,NULL,1);

INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR TIPO TRANSACCION', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 35
('ACTUALIZAR TIPO TRANSACCION', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('FILTRAR TIPO TRANSACCION POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('LISTAR ULTIMOS 10 TIPOS TRANSACCIONES', GETDATE(), GETDATE(), NULL,NULL,NULL,1);


INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR TIPO TRANSACCION ROL', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 39
('ACTUALIZAR TIPO TRANSACCION ROL', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('FILTRAR TIPO TRANSACCION ROL POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('LISTAR ULTIMOS 10 TIPOS TRANSACCIONES ROLES', GETDATE(), GETDATE(), NULL,NULL,NULL,1);


INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR TIPO TRANSACCION ESTADO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 43
('ACTUALIZAR TIPO TRANSACCION ESTADO', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('FILTRAR TIPO TRANSACCION ESTADO POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('LISTAR ULTIMOS 10 TIPOS TRANSACCIONES ESTADOS', GETDATE(), GETDATE(), NULL,NULL,NULL,1);

INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR USUARIO ROL', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 47
('ACTUALIZAR USUARIO ROL', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('FILTRAR USUARIO ROL ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1),
('LISTAR ROLES DE USUARIO', GETDATE(), GETDATE(), NULL,NULL,NULL,1);

INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR MENU', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 51
('ACTUALIZAR MENU', GETDATE(), GETDATE(), NULL,NULL,NULL,1), --52
('FILTRAR MENU ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1),-- 53
('LISTAR ULTIMOS 10 MENUS', GETDATE(), GETDATE(), NULL,NULL,NULL,1); --54

INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR MENU ROL', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 55
('ACTUALIZAR MENU ROL', GETDATE(), GETDATE(), NULL,NULL,NULL,1), --56
('FILTRAR MENU ROL ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1),-- 57
('LISTAR ULTIMOS 10 MENUS ROLES', GETDATE(), GETDATE(), NULL,NULL,NULL,1); --58

INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR BECA PROGRAMA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 59
('ACTUALIZAR BECA PROGRAMA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 60
('FILTRAR BECA PROGRAMA POR TIPO PROGRAMA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 61
('FILTRAR BECA PROGRAMA POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 62
('FILTRAR BECA PROGRAMA POR NOMBRE', GETDATE(), GETDATE(), NULL,NULL,NULL,1); -- 63

INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR BECA CRITERIO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 64
('FILTRAR BECA CRITERIO POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 65
('FILTRAR BECA CRITERIO POR ID PROGRAMA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 66
('ACTUALIZAR BECA CRITERIO', GETDATE(), GETDATE(), NULL,NULL,NULL,1); -- 67

INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR SOLICITUD BECA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 68
('ACTUALIZAR SOLICITUD BECA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 69
('FILTRAR SOLICITUD BECA POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 70
('FILTRAR SOLICITUD BECA POR ID PROGRAMA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 71
('FILTRAR SOLICITUD BECA POR ESTUDIANTE', GETDATE(), GETDATE(), NULL,NULL,NULL,1); -- 72

INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR MATERIA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 73
('ACTUALIZAR MATERIA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 74
('FILTRAR MATERIA POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 75
('FILTRAR MATERIA POR CODIGO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 76
('FILTRAR MATERIA POR NOMBRE', GETDATE(), GETDATE(), NULL,NULL,NULL,1); -- 77

INSERT INTO cls_tipos_transacciones(Nombre_Tipo_Transaccion,Fecha_Creacion,Fecha_Modificacion,Id_Creador,Id_Modificador,Id_Transaccion,Activo) VALUES
('AGREGAR PERIODO ACADEMICO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 78
('ACTUALIZAR PERIODO ACADEMICO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 79
('FILTRAR PERIODO POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 80
('FILTRAR PERIODO POR CODIGO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 81
('AGREGAR CONVOCATORIA BECA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 82
('ACTUALIZAR CONVOCATORIA BECA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 83
('FILTRAR CONVOCATORIA POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 84
('FILTRAR CONVOCATORIA POR ID PROGRAMA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 85
('FILTRAR CONVOCATORIA POR ID PERIODO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 86
('AGREGAR SANCIÓN ACADÉMICA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 87
('FILTRAR SANCIÓN POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 88
('FILTRAR SANCIÓN POR ESTUDIANTE', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 89
('ACTUALIZAR SANCIÓN ACADÉMICA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 90
('AGREGAR MATERIA PERÍODO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 91
('ACTUALIZAR MATERIA PERÍODO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 92
('FILTRAR MATERIA PERÍODO POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 93
('FILTRAR MATERIA PERÍODO POR MATERIA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 94
('FILTRAR MATERIA PERÍODO POR PERÍODO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 95
('AGREGAR SECCIÓN', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 96
('ACTUALIZAR SECCIÓN', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 97
('FILTRAR SECCIÓN POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 98
('FILTRAR SECCIÓN POR DOCENTE', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 99
('FILTRAR SECCIÓN POR MATERIA PERÍODO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 100
('AGREGAR GRUPO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 101
('ACTUALIZAR GRUPO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 102
('FILTRAR GRUPO POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 103
('FILTRAR GRUPO POR PERÍODO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 104
('AGREGAR GRUPO SECCIÓN', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 105
('ACTUALIZAR GRUPO SECCIÓN', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 106
('FILTRAR GRUPO SECCIÓN POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 107
('FILTRAR GRUPO SECCIÓN POR GRUPO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 108
('FILTRAR GRUPO SECCIÓN POR SECCIÓN', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 109
('AGREGAR INSCRIPCIÓN', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 110
('ACTUALIZAR INSCRIPCIÓN', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 111
('FILTRAR INSCRIPCIÓN POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 112
('FILTRAR INSCRIPCIÓN POR ESTUDIANTE', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 113
('FILTRAR INSCRIPCIÓN POR SECCIÓN', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 114
('AGREGAR GRUPO INSCRIPCIÓN', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 115
('ACTUALIZAR GRUPO INSCRIPCIÓN', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 116
('FILTRAR GRUPO INSCRIPCIÓN POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 117
('FILTRAR GRUPO INSCRIPCIÓN POR GRUPO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 118
('FILTRAR GRUPO INSCRIPCIÓN POR INSCRIPCIÓN', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 119
('AGREGAR EVALUACIÓN MODELO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 120
('ACTUALIZAR EVALUACIÓN MODELO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 121
('FILTRAR EVALUACIÓN MODELO POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 122
('FILTRAR EVALUACIÓN MODELO POR MATERIA PERÍODO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 123
('AGREGAR EVALUACIÓN INSTANCIA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 124
('ACTUALIZAR EVALUACIÓN INSTANCIA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 125
('FILTRAR EVALUACIÓN INSTANCIA POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 126
('FILTRAR EVALUACIÓN INSTANCIA POR SECCIÓN', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 127
('AGREGAR EVALUACIÓN ALUMNO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 128
('ACTUALIZAR EVALUACIÓN ALUMNO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 129
('FILTRAR EVALUACIÓN ALUMNO POR ID', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 130
('FILTRAR EVALUACIÓN ALUMNO POR ESTUDIANTE', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 131
('FILTRAR EVALUACIÓN ALUMNO POR INSTANCIA', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 132
('OBTENER ESTUDIANTE POR NUMERO DE DOCUMENTO', GETDATE(), GETDATE(), NULL,NULL,NULL,1), -- 133
('LISTAR ESTUDIANTES CON SANCIONES', GETDATE(), GETDATE(), NULL,NULL,NULL,1); -- 134

/* */
INSERT INTO cls_transacciones_roles (Id_Tipo_Transaccion, Id_Rol, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo) VALUES
(1, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(2, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(3, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(4, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(5, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(6, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(7, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(8, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(9, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(10, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(11, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(12, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(13, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(14, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(15, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(16, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(17, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(18, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(19, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(20, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(21, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(22, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(23, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(24, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(25, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(26, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(27, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(28, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(29, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(30, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(31, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(32, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(33, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(34, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(35, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(36, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(37, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(38, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(39, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(40, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(41, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(42, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(43, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(44, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(45, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(46, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(47, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(48, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(49, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(50, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(51, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(52, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(53, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(54, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(55, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(56, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(57, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(58, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(59, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(60, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(61, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(62, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(63, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(64, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(65, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(66, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(67, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(68, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(69, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(70, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(71, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(72, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(73, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(74, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(75, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(76, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(77, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(78, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(79, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(80, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(81, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(82, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(83, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(84, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(85, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(86, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(87, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(88, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(89, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(90, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(91, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(92, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(93, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(94, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(95, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(96, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(97, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(98, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(99, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(100, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(101, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(102, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(103, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(104, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(105, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(106, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(107, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(108, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(109, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(110, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(111, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(112, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(113, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(114, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(115, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(116, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(117, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(118, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(119, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(120, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(121, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(122, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(123, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(124, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(125, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(126, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(127, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(128, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(129, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(130, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(131, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(132, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(133, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(134, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1);

INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(15,1,GETDATE(),GETDATE(),1),
(15,3,GETDATE(),GETDATE(),1),
(16,1,GETDATE(),GETDATE(),1),
(16,2,GETDATE(),GETDATE(),1); 

INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(20,1,GETDATE(),GETDATE(),1),
(20,3,GETDATE(),GETDATE(),1),
(21,1,GETDATE(),GETDATE(),1),
(21,2,GETDATE(),GETDATE(),1); 

-- ============================================================
-- ESTADOS LÓGICOS PARA TRANSACCIONES DE AGREGAR Y ACTUALIZAR
-- ============================================================
-- AGREGAR TIPOS CATALOGOS (6) y ACTUALIZAR TIPOS CATALOGOS (7)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(6,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(6,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(7,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(7,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR CATALOGOS (11) y ACTUALIZAR CATALOGOS (12)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(11,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(11,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(12,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(12,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR PERSONAS (16) y ACTUALIZAR PERSONAS (17)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(16,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(16,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(17,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(17,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR CONTACTO (28) y ACTUALIZAR CONTACTO (29)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(28,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(28,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(29,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(29,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR ROL (31) y ACTUALIZAR ROL (32)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(31,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(31,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(32,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(32,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR TIPO TRANSACCION (35) y ACTUALIZAR TIPO TRANSACCION (36)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(35,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(35,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(36,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(36,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR TIPO TRANSACCION ROL (39) y ACTUALIZAR TIPO TRANSACCION ROL (40)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(39,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(39,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(40,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(40,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR TIPO TRANSACCION ESTADO (43) y ACTUALIZAR TIPO TRANSACCION ESTADO (44)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(43,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(43,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(44,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(44,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR USUARIO ROL (47) y ACTUALIZAR USUARIO ROL (48)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(47,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(47,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(48,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(48,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR MENU (51) y ACTUALIZAR MENU (52)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(51,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(51,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(52,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(52,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR MENU ROL (55) y ACTUALIZAR MENU ROL (56)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(55,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(55,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(56,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(56,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR BECA PROGRAMA (59) y ACTUALIZAR BECA PROGRAMA (60)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(59,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(59,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(59,4,GETDATE(),GETDATE(),1), -- AGREGAR: EN REVISION
(60,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(60,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR BECA CRITERIO (64) y ACTUALIZAR BECA CRITERIO (67)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(64,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(64,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(67,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(67,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR SOLICITUD BECA (68) y ACTUALIZAR SOLICITUD BECA (69)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(68,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(68,4,GETDATE(),GETDATE(),1), -- AGREGAR: EN REVISION
(69,3,GETDATE(),GETDATE(),1), -- ACTUALIZAR: PENDIENTE
(69,4,GETDATE(),GETDATE(),1), -- ACTUALIZAR: EN REVISION
(69,5,GETDATE(),GETDATE(),1), -- ACTUALIZAR: APROBADA
(69,6,GETDATE(),GETDATE(),1); -- ACTUALIZAR: RECHAZADA

-- AGREGAR MATERIA (73) y ACTUALIZAR MATERIA (74)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(73,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(73,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(74,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(74,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR PERIODO ACADEMICO (78) y ACTUALIZAR PERIODO ACADEMICO (79)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(78,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(78,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(78,7,GETDATE(),GETDATE(),1), -- AGREGAR: PLANIFICADA
(79,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(79,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR CONVOCATORIA BECA (82) y ACTUALIZAR CONVOCATORIA BECA (83)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(82,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(82,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(82,4,GETDATE(),GETDATE(),1), -- AGREGAR: EN REVISION
(82,7,GETDATE(),GETDATE(),1), -- AGREGAR: PLANIFICADA
(83,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(83,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR SANCIÓN ACADÉMICA (87) y ACTUALIZAR SANCIÓN ACADÉMICA (90)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(87,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO (sanción aplicada inmediatamente)
(87,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE (requiere validación)
(87,4,GETDATE(),GETDATE(),1), -- AGREGAR: EN REVISION (en proceso de revisión)
(90,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO (activar sanción)
(90,2,GETDATE(),GETDATE(),1), -- ACTUALIZAR: INACTIVO (anular/desactivar sanción)
(90,3,GETDATE(),GETDATE(),1), -- ACTUALIZAR: PENDIENTE (poner en pendiente)
(90,4,GETDATE(),GETDATE(),1), -- ACTUALIZAR: EN REVISION (poner en revisión/apelación)
(90,5,GETDATE(),GETDATE(),1), -- ACTUALIZAR: APROBADA (aprobada después de revisión)
(90,6,GETDATE(),GETDATE(),1); -- ACTUALIZAR: RECHAZADA (rechazada después de revisión/apelación)

-- AGREGAR MATERIA PERÍODO (91) y ACTUALIZAR MATERIA PERÍODO (92)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(91,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(91,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(91,4,GETDATE(),GETDATE(),1), -- AGREGAR: EN REVISION
(92,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(92,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR SECCIÓN (96) y ACTUALIZAR SECCIÓN (97)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(96,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(96,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(96,4,GETDATE(),GETDATE(),1), -- AGREGAR: EN REVISION
(97,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(97,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR GRUPO (101) y ACTUALIZAR GRUPO (102)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(101,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(101,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(102,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(102,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR GRUPO SECCIÓN (105) y ACTUALIZAR GRUPO SECCIÓN (106)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(105,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(105,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(106,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(106,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR INSCRIPCIÓN (110) y ACTUALIZAR INSCRIPCIÓN (111)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(110,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(110,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(110,4,GETDATE(),GETDATE(),1), -- AGREGAR: EN REVISION
(111,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(111,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR GRUPO INSCRIPCIÓN (115) y ACTUALIZAR GRUPO INSCRIPCIÓN (116)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(115,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(115,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(116,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(116,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR EVALUACIÓN MODELO (120) y ACTUALIZAR EVALUACIÓN MODELO (121)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(120,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(120,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(120,4,GETDATE(),GETDATE(),1), -- AGREGAR: EN REVISION
(121,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(121,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR EVALUACIÓN INSTANCIA (124) y ACTUALIZAR EVALUACIÓN INSTANCIA (125)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(124,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(124,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(124,4,GETDATE(),GETDATE(),1), -- AGREGAR: EN REVISION
(125,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(125,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- AGREGAR EVALUACIÓN ALUMNO (128) y ACTUALIZAR EVALUACIÓN ALUMNO (129)
INSERT INTO cls_transacciones_estados(Id_Tipo_Transaccion,Id_Estado,Fecha_Creacion,Fecha_Modificacion,Activo) VALUES
(128,1,GETDATE(),GETDATE(),1), -- AGREGAR: ACTIVO
(128,3,GETDATE(),GETDATE(),1), -- AGREGAR: PENDIENTE
(128,4,GETDATE(),GETDATE(),1), -- AGREGAR: EN REVISION
(129,1,GETDATE(),GETDATE(),1), -- ACTUALIZAR: ACTIVO
(129,2,GETDATE(),GETDATE(),1); -- ACTUALIZAR: INACTIVO

-- ============================================================
-- INSERTS ADICIONALES DE CATÁLOGOS NECESARIOS
-- ============================================================

INSERT INTO cls_tipos_catalogos (Nombre_Tipo_Catalogo, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo) VALUES
('TIPO PERIODO', GETDATE(), GETDATE(), NULL, NULL, NULL, 1), -- 10
('MODALIDAD PROGRAMA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1), -- 11
('MONEDA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1), -- 12
('TIPO CRITERIO', GETDATE(), GETDATE(), NULL, NULL, NULL, 1), -- 13
('JORNADA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1), -- 14
('TIPO SECCION', GETDATE(), GETDATE(), NULL, NULL, NULL, 1), -- 15
('AULA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1), -- 16
('TIPO GRUPO', GETDATE(), GETDATE(), NULL, NULL, NULL, 1), -- 17
('TIPO INSCRIPCION', GETDATE(), GETDATE(), NULL, NULL, NULL, 1), -- 18
('ROL GRUPO', GETDATE(), GETDATE(), NULL, NULL, NULL, 1), -- 19
('TIPO VINCULO', GETDATE(), GETDATE(), NULL, NULL, NULL, 1), -- 20
('METODO CALCULO', GETDATE(), GETDATE(), NULL, NULL, NULL, 1), -- 21
('TIPO APROBACION', GETDATE(), GETDATE(), NULL, NULL, NULL, 1), -- 22
('TIPO DECISION', GETDATE(), GETDATE(), NULL, NULL, NULL, 1), -- 23
('TIPO FALTA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1); -- 24

INSERT INTO cls_catalogos (Id_Tipo_Catalogo, Nombre_Catalogo, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo) VALUES
-- TIPO PERIODO (10)
(10, 'CUATRIMESTRE', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(10, 'SEMESTRE', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(10, 'ANUAL', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
-- MODALIDAD PROGRAMA (11)
(11, 'PRESENCIAL', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(11, 'VIRTUAL', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(11, 'HIBRIDO', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
-- MONEDA (12)
(12, 'CORDOBA NIO', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(12, 'DOLAR USD', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
-- TIPO CRITERIO (13)
(13, 'PROMEDIO', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(13, 'CREDITOS', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(13, 'SANCIONES', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(13, 'ASISTENCIA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
-- JORNADA (14)
(14, 'MATUTINA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(14, 'VESPERTINA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(14, 'NOCTURNA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(14, 'SABATINA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
-- TIPO SECCION (15)
(15, 'TEORICA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(15, 'PRACTICA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(15, 'LABORATORIO', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(15, 'TALLER', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
-- AULA (16)
(16, 'A-101', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(16, 'A-102', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(16, 'LAB-201', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(16, 'LAB-202', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(16, 'VIRTUAL', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
-- TIPO GRUPO (17)
(17, 'ACADEMICO', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(17, 'INVESTIGACION', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(17, 'EXTENSION', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
-- TIPO INSCRIPCION (18)
(18, 'REGULAR', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(18, 'ESPECIAL', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(18, 'AUDITORIA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
-- ROL GRUPO (19)
(19, 'ESTUDIANTE', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(19, 'DELEGADO', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(19, 'SUBDELEGADO', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
-- TIPO VINCULO (20)
(20, 'PRINCIPAL', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(20, 'SECUNDARIO', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
-- METODO CALCULO (21)
(21, 'PROMEDIO SIMPLE', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(21, 'PROMEDIO PONDERADO', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(21, 'RUBRICA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
-- TIPO APROBACION (22)
(22, 'CREACION', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(22, 'REVISION', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(22, 'PUBLICACION', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
-- TIPO DECISION (23)
(23, 'APROBADA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(23, 'RECHAZADA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(23, 'PENDIENTE', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
-- TIPO FALTA (24)
(24, 'ACADEMICA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),
(24, 'DISCIPLINARIA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1);

-- ============================================================
-- PERÍODOS ACADÉMICOS
-- ============================================================
INSERT INTO tbl_periodos_academicos (
    Codigo_Periodo, Nombre_Periodo, Id_Tipo_Periodo, Fecha_Inicio, Fecha_Fin, 
    Fecha_Cierre_Calificaciones, Es_Periodo_Actual, Permite_Inscripciones, 
    Codigo_Integracion, Observaciones, Id_Estado, Id_Estado_Publicacion,
    Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion
) VALUES
('2024-I', 'Primer Cuatrimestre 2024', 10, '2024-01-15', '2024-04-30', '2024-05-15', 0, 0, 'PER-2024-I', 'Período académico primer cuatrimestre', 1, 1, GETDATE(), GETDATE(), 1, 1, NULL),
('2024-II', 'Segundo Cuatrimestre 2024', 10, '2024-05-15', '2024-08-31', '2024-09-15', 0, 0, 'PER-2024-II', 'Período académico segundo cuatrimestre', 1, 1, GETDATE(), GETDATE(), 1, 1, NULL),
('2024-III', 'Tercer Cuatrimestre 2024', 10, '2024-09-15', '2024-12-31', '2025-01-15', 1, 1, 'PER-2024-III', 'Período académico actual', 1, 5, GETDATE(), GETDATE(), 1, 1, NULL);

-- ============================================================
-- MATERIAS
-- ============================================================
INSERT INTO cls_materias (
    Codigo_Materia, Nombre_Materia, Fecha_Creacion, Fecha_Modificacion,
    Id_Creador, Id_Modificador, Id_Transaccion, Activo
) VALUES
('MAT-101', 'MATEMÁTICA BÁSICA', GETDATE(), GETDATE(), 1, 1, NULL, 1),
('PROG-201', 'PROGRAMACIÓN I', GETDATE(), GETDATE(), 1, 1, NULL, 1),
('PROG-202', 'PROGRAMACIÓN II', GETDATE(), GETDATE(), 1, 1, NULL, 1),
('BD-301', 'BASES DE DATOS', GETDATE(), GETDATE(), 1, 1, NULL, 1),
('WEB-302', 'DESARROLLO WEB', GETDATE(), GETDATE(), 1, 1, NULL, 1),
('ING-401', 'INGENIERÍA DE SOFTWARE', GETDATE(), GETDATE(), 1, 1, NULL, 1),
('EST-501', 'ESTADÍSTICA', GETDATE(), GETDATE(), 1, 1, NULL, 1),
('ETI-201', 'ÉTICA PROFESIONAL', GETDATE(), GETDATE(), 1, 1, NULL, 1);

-- ============================================================
-- MATERIAS PERÍODOS (Asignar materias a períodos)
-- ============================================================
INSERT INTO cls_materias_periodos (
    Id_Materia, Id_Periodo_Academico, Codigo_Plan, Id_Jornada, Modalidad,
    Horas_Teoricas, Horas_Practicas, Porcentaje_Asistencia_Minima, Id_Estado,
    Fecha_Publicacion, Id_Usuario_Publicador, Observaciones, Fecha_Creacion,
    Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo
) VALUES
-- Período 2024-III (Id_Periodo = 3)
(1, 3, 'PLAN-2020', 14, 'PRESENCIAL', 40, 20, 75.00, 1, GETDATE(), 1, 'Materia básica del plan de estudios', GETDATE(), GETDATE(), 1, 1, NULL, 1),
(2, 3, 'PLAN-2020', 14, 'PRESENCIAL', 60, 40, 80.00, 1, GETDATE(), 1, 'Programación orientada a objetos', GETDATE(), GETDATE(), 1, 1, NULL, 1),
(3, 3, 'PLAN-2020', 15, 'HIBRIDO', 50, 30, 75.00, 1, GETDATE(), 1, 'Continuación de programación', GETDATE(), GETDATE(), 1, 1, NULL, 1),
(4, 3, 'PLAN-2020', 14, 'PRESENCIAL', 50, 40, 80.00, 1, GETDATE(), 1, 'Diseño y administración de BD', GETDATE(), GETDATE(), 1, 1, NULL, 1),
(5, 3, 'PLAN-2020', 15, 'VIRTUAL', 40, 20, 70.00, 1, GETDATE(), 1, 'Desarrollo frontend y backend', GETDATE(), GETDATE(), 1, 1, NULL, 1),
(6, 3, 'PLAN-2020', 14, 'PRESENCIAL', 60, 30, 80.00, 1, GETDATE(), 1, 'Metodologías ágiles', GETDATE(), GETDATE(), 1, 1, NULL, 1),
(8, 3, 'PLAN-2020', 14, 'PRESENCIAL', 30, 0, 75.00, 1, GETDATE(), 1, 'Formación integral', GETDATE(), GETDATE(), 1, 1, NULL, 1);

-- ============================================================
-- SECCIONES (Asignar docentes a materias-períodos)
-- ============================================================
INSERT INTO tbl_secciones (
    Codigo_Seccion, Id_Materia_Periodo, Id_Docente, Id_Tipo_Seccion, Id_Aula,
    Horario_Descripcion, Modalidad, Cupo_Maximo, Requiere_Asistencia,
    Porcentaje_Asistencia_Minima, Id_Estado, Id_Estado_Publicacion,
    Fecha_Publicacion, Fecha_Cierre, Codigo_Firma, Id_Usuario_Publicador,
    Observaciones, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador,
    Id_Transaccion, Activo
) VALUES
-- Secciones para MAT-101 (Id_Materia_Periodo = 1)
('MAT-101-A', 1, 2, 15, 16, 'Lunes y Miércoles 8:00-10:00', 'PRESENCIAL', 30, 1, 75.00, 1, 5, GETDATE(), NULL, 'FIRMA-MAT-101-A', 1, 'Sección matutina', GETDATE(), GETDATE(), 1, 1, NULL, 1),
-- Secciones para PROG-201 (Id_Materia_Periodo = 2)
('PROG-201-A', 2, 2, 15, 16, 'Martes y Jueves 8:00-11:00', 'PRESENCIAL', 25, 1, 80.00, 1, 5, GETDATE(), NULL, 'FIRMA-PROG-201-A', 1, 'Sección con laboratorio', GETDATE(), GETDATE(), 1, 1, NULL, 1),
('PROG-201-B', 2, 6, 15, 17, 'Martes y Jueves 14:00-17:00', 'PRESENCIAL', 25, 1, 80.00, 1, 5, GETDATE(), NULL, 'FIRMA-PROG-201-B', 1, 'Sección vespertina', GETDATE(), GETDATE(), 1, 1, NULL, 1),
-- Secciones para PROG-202 (Id_Materia_Periodo = 3)
('PROG-202-A', 3, 2, 15, NULL, 'Lunes y Miércoles 14:00-17:00', 'HIBRIDO', 20, 1, 75.00, 1, 5, GETDATE(), NULL, 'FIRMA-PROG-202-A', 1, 'Modalidad híbrida', GETDATE(), GETDATE(), 1, 1, NULL, 1),
-- Secciones para BD-301 (Id_Materia_Periodo = 4)
('BD-301-A', 4, 3, 15, 18, 'Viernes 8:00-13:00', 'PRESENCIAL', 30, 1, 80.00, 1, 5, GETDATE(), NULL, 'FIRMA-BD-301-A', 1, 'Sección intensiva', GETDATE(), GETDATE(), 1, 1, NULL, 1),
-- Secciones para WEB-302 (Id_Materia_Periodo = 5)
('WEB-302-A', 5, 6, 15, NULL, 'Sábado 8:00-12:00', 'VIRTUAL', 35, 1, 70.00, 1, 5, GETDATE(), NULL, 'FIRMA-WEB-302-A', 1, 'Clases virtuales', GETDATE(), GETDATE(), 1, 1, NULL, 1),
-- Secciones para ING-401 (Id_Materia_Periodo = 6)
('ING-401-A', 6, 3, 15, 16, 'Lunes y Miércoles 10:00-13:00', 'PRESENCIAL', 25, 1, 80.00, 1, 5, GETDATE(), NULL, 'FIRMA-ING-401-A', 1, 'Proyecto integrador', GETDATE(), GETDATE(), 1, 1, NULL, 1),
-- Secciones para ETI-201 (Id_Materia_Periodo = 7)
('ETI-201-A', 7, 2, 15, 16, 'Viernes 14:00-17:00', 'PRESENCIAL', 40, 1, 75.00, 1, 5, GETDATE(), NULL, 'FIRMA-ETI-201-A', 1, 'Formación integral', GETDATE(), GETDATE(), 1, 1, NULL, 1);

-- ============================================================
-- GRUPOS
-- ============================================================
INSERT INTO tbl_grupos (
    Codigo_Grupo, Nombre_Grupo, Id_Periodo, Id_Tipo_Grupo, Id_Coordinador,
    Id_Jornada, Id_Estado, Fecha_Cierre, Observaciones, Codigo_Seguimiento,
    Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo
) VALUES
('GRP-2024-III-A', 'Grupo Académico A - 2024-III', 3, 17, 3, 14, 1, NULL, 'Grupo principal del período', 'SEG-GRP-2024-III-A', GETDATE(), GETDATE(), 1, 1, NULL, 1),
('GRP-2024-III-B', 'Grupo Académico B - 2024-III', 3, 17, 3, 15, 1, NULL, 'Grupo secundario del período', 'SEG-GRP-2024-III-B', GETDATE(), GETDATE(), 1, 1, NULL, 1);

-- ============================================================
-- GRUPOS SECCIONES (Vincular secciones a grupos)
-- ============================================================
INSERT INTO cls_grupos_secciones (
    Id_Grupo, Id_Seccion, Id_Tipo_Vinculo, Prioridad, Fecha_Asignacion,
    Fecha_Desasignacion, Motivo_Desasignacion, Fecha_Creacion, Fecha_Modificacion,
    Id_Creador, Id_Modificador, Id_Transaccion, Activo
) VALUES
-- Grupo 1 con varias secciones
(1, 1, 20, 1, GETDATE(), NULL, NULL, GETDATE(), GETDATE(), 1, 1, NULL, 1),
(1, 2, 20, 1, GETDATE(), NULL, NULL, GETDATE(), GETDATE(), 1, 1, NULL, 1),
(1, 4, 20, 1, GETDATE(), NULL, NULL, GETDATE(), GETDATE(), 1, 1, NULL, 1),
(1, 5, 20, 1, GETDATE(), NULL, NULL, GETDATE(), GETDATE(), 1, 1, NULL, 1),
(1, 7, 20, 1, GETDATE(), NULL, NULL, GETDATE(), GETDATE(), 1, 1, NULL, 1),
(1, 8, 20, 1, GETDATE(), NULL, NULL, GETDATE(), GETDATE(), 1, 1, NULL, 1),
-- Grupo 2 con otras secciones
(2, 3, 20, 1, GETDATE(), NULL, NULL, GETDATE(), GETDATE(), 1, 1, NULL, 1),
(2, 6, 20, 1, GETDATE(), NULL, NULL, GETDATE(), GETDATE(), 1, 1, NULL, 1);

-- ============================================================
-- INSCRIPCIONES (Estudiantes inscritos en secciones)
-- ============================================================
INSERT INTO tbl_inscripciones (
    Codigo_Inscripcion, Id_Seccion, Id_Estudiante, Id_Tipo_Inscripcion, Id_Estado,
    Fecha_Creacion, Fecha_Modificacion, Fecha_Validacion, Fecha_Retiro, Motivo_Retiro,
    Promedio_Acumulado, Total_Faltas, Es_Repetidor, En_Riesgo_Academico,
    Id_Creador, Id_Modificador, Id_Usuario_Validador, Id_Transaccion, Activo
) VALUES
-- Estudiantes en MAT-101-A (Id_Seccion = 1)
('INS-2024-III-001', 1, 4, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, NULL, 0, 0, 0, 1, 1, 1, NULL, 1),
('INS-2024-III-002', 1, 5, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, NULL, 0, 0, 0, 1, 1, 1, NULL, 1),
('INS-2024-III-003', 1, 8, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, NULL, 2, 0, 1, 1, 1, 1, NULL, 1),
-- Estudiantes en PROG-201-A (Id_Seccion = 2)
('INS-2024-III-004', 2, 4, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, 85.50, 1, 0, 0, 1, 1, 1, NULL, 1),
('INS-2024-III-005', 2, 5, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, 92.00, 0, 0, 0, 1, 1, 1, NULL, 1),
('INS-2024-III-006', 2, 9, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, 78.50, 3, 0, 1, 1, 1, 1, NULL, 1),
-- Estudiantes en PROG-201-B (Id_Seccion = 3)
('INS-2024-III-007', 3, 8, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, NULL, 0, 0, 0, 1, 1, 1, NULL, 1),
('INS-2024-III-008', 3, 10, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, NULL, 0, 0, 0, 1, 1, 1, NULL, 1),
-- Estudiantes en PROG-202-A (Id_Seccion = 4)
('INS-2024-III-009', 4, 4, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, 88.00, 0, 0, 0, 1, 1, 1, NULL, 1),
('INS-2024-III-010', 4, 5, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, 90.50, 0, 0, 0, 1, 1, 1, NULL, 1),
-- Estudiantes en BD-301-A (Id_Seccion = 5)
('INS-2024-III-011', 5, 4, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, NULL, 0, 0, 0, 1, 1, 1, NULL, 1),
('INS-2024-III-012', 5, 9, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, NULL, 1, 0, 0, 1, 1, 1, NULL, 1),
-- Estudiantes en WEB-302-A (Id_Seccion = 6)
('INS-2024-III-013', 6, 5, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, NULL, 0, 0, 0, 1, 1, 1, NULL, 1),
('INS-2024-III-014', 6, 10, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, NULL, 0, 0, 0, 1, 1, 1, NULL, 1),
-- Estudiantes en ING-401-A (Id_Seccion = 7)
('INS-2024-III-015', 7, 4, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, NULL, 0, 0, 0, 1, 1, 1, NULL, 1),
('INS-2024-III-016', 7, 5, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, NULL, 0, 0, 0, 1, 1, 1, NULL, 1),
-- Estudiantes en ETI-201-A (Id_Seccion = 8)
('INS-2024-III-017', 8, 4, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, NULL, 0, 0, 0, 1, 1, 1, NULL, 1),
('INS-2024-III-018', 8, 5, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, NULL, 0, 0, 0, 1, 1, 1, NULL, 1),
('INS-2024-III-019', 8, 8, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, NULL, 0, 0, 0, 1, 1, 1, NULL, 1),
('INS-2024-III-020', 8, 9, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, NULL, 0, 0, 0, 1, 1, 1, NULL, 1),
('INS-2024-III-021', 8, 10, 18, 1, GETDATE(), GETDATE(), GETDATE(), NULL, NULL, NULL, 0, 0, 0, 1, 1, 1, NULL, 1);

-- ============================================================
-- GRUPOS INSCRIPCIONES (Asignar estudiantes a grupos)
-- ============================================================
INSERT INTO tbl_grupos_inscripciones (
    Id_Grupo, Id_Inscripcion, Id_Rol_Grupo, Id_Estado, Fecha_Asignacion,
    Fecha_Baja, Motivo_Baja, Es_Delegado, Observaciones, Fecha_Creacion,
    Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo
) VALUES
-- Grupo 1 - Estudiantes principales
(1, 1, 19, 1, GETDATE(), NULL, NULL, 0, NULL, GETDATE(), GETDATE(), 1, 1, NULL, 1),
(1, 4, 19, 1, GETDATE(), NULL, NULL, 1, 'Delegado del grupo', GETDATE(), GETDATE(), 1, 1, NULL, 1),
(1, 9, 19, 1, GETDATE(), NULL, NULL, 0, NULL, GETDATE(), GETDATE(), 1, 1, NULL, 1),
(1, 11, 19, 1, GETDATE(), NULL, NULL, 0, NULL, GETDATE(), GETDATE(), 1, 1, NULL, 1),
(1, 15, 19, 1, GETDATE(), NULL, NULL, 0, NULL, GETDATE(), GETDATE(), 1, 1, NULL, 1),
(1, 17, 19, 1, GETDATE(), NULL, NULL, 0, NULL, GETDATE(), GETDATE(), 1, 1, NULL, 1),
-- Grupo 2 - Otros estudiantes
(2, 7, 19, 1, GETDATE(), NULL, NULL, 0, NULL, GETDATE(), GETDATE(), 1, 1, NULL, 1),
(2, 13, 19, 1, GETDATE(), NULL, NULL, 1, 'Delegado del grupo', GETDATE(), GETDATE(), 1, 1, NULL, 1),
(2, 19, 19, 1, GETDATE(), NULL, NULL, 0, NULL, GETDATE(), GETDATE(), 1, 1, NULL, 1);

-- ============================================================
-- PROGRAMAS DE BECAS
-- ============================================================
INSERT INTO cls_becas_programas (
    Codigo_Programa, Nombre_Programa, Descripcion, Id_Tipo_Programa, Id_Modalidad_Programa,
    Fecha_Vigencia_Inicio, Fecha_Vigencia_Fin, Monto_Maximo, Id_Moneda, Promedio_Minimo,
    Creditos_Minimos, Niveles_Aprobacion, Requiere_Sin_Sanciones, Requiere_Carta_Compromiso,
    Id_Estado_Programa, Activo, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion
) VALUES
('BEC-MAE-001', 'BECA MAESTRÍA EXCELENCIA', 'Programa de becas para estudiantes de maestría con excelencia académica', 43, 11, '2024-01-01', '2024-12-31', 50000.00, 12, 90.00, 120, 3, 1, 1, 1, 1, GETDATE(), GETDATE(), 1, 1, NULL),
('BEC-POS-001', 'BECA POSGRADO INVESTIGACIÓN', 'Beca para estudiantes de posgrado que realizan investigación', 44, 11, '2024-01-01', '2024-12-31', 75000.00, 12, 85.00, 100, 2, 1, 0, 1, 1, GETDATE(), GETDATE(), 1, 1, NULL),
('BEC-EXC-001', 'BECA EXCELENCIA ACADÉMICA', 'Beca para estudiantes con promedio superior a 95', 42, 11, '2024-01-01', '2024-12-31', 30000.00, 12, 95.00, 80, 2, 1, 0, 1, 1, GETDATE(), GETDATE(), 1, 1, NULL);

-- ============================================================
-- CRITERIOS DE BECAS
-- ============================================================
INSERT INTO cls_becas_criterios (
    Id_Programa, Codigo, Nombre_Criterio, Clave_Criterio, Valor_Criterio,
    Tipo_Dato_Valor, Id_Tipo_Criterio, Operador_Comparacion, Valor_Numerico_Minimo,
    Valor_Numerico_Maximo, Valor_Texto, Valor_Booleano, Peso_Criterio, Prioridad,
    Es_Excluyente, Fuente_Validacion, Expresion_Validacion, Requiere_Soporte,
    Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Activo
) VALUES
-- Criterios para BECA MAESTRÍA EXCELENCIA (Id_Programa = 1)
(1, 'CRIT-001', 'Promedio Mínimo', 'PROMEDIO_MIN', '90', 'NUMERICO', 13, '>=', 90.00, NULL, NULL, NULL, 40.00, 1, 1, 'tbl_inscripciones', 'Promedio_Acumulado >= 90', 0, GETDATE(), GETDATE(), 1, 1, 1),
(1, 'CRIT-002', 'Sin Sanciones Activas', 'SIN_SANCIONES', 'true', 'BOOLEANO', 13, '=', NULL, NULL, NULL, 1, 30.00, 2, 1, 'tbl_sanciones_academicas', 'Total_Sanciones_Activas = 0', 0, GETDATE(), GETDATE(), 1, 1, 1),
(1, 'CRIT-003', 'Créditos Mínimos', 'CREDITOS_MIN', '120', 'NUMERICO', 13, '>=', 120.00, NULL, NULL, NULL, 30.00, 3, 0, 'tbl_inscripciones', 'Creditos_Aprobados >= 120', 1, GETDATE(), GETDATE(), 1, 1, 1),
-- Criterios para BECA POSGRADO INVESTIGACIÓN (Id_Programa = 2)
(2, 'CRIT-004', 'Promedio Mínimo', 'PROMEDIO_MIN', '85', 'NUMERICO', 13, '>=', 85.00, NULL, NULL, NULL, 50.00, 1, 1, 'tbl_inscripciones', 'Promedio_Acumulado >= 85', 0, GETDATE(), GETDATE(), 1, 1, 1),
(2, 'CRIT-005', 'Sin Sanciones', 'SIN_SANCIONES', 'true', 'BOOLEANO', 13, '=', NULL, NULL, NULL, 1, 50.00, 2, 1, 'tbl_sanciones_academicas', 'Total_Sanciones_Activas = 0', 0, GETDATE(), GETDATE(), 1, 1, 1);

-- ============================================================
-- CONVOCATORIAS DE BECAS
-- ============================================================
INSERT INTO tbl_becas_convocatorias (
    Codigo_Convocatoria, Id_Programa, Id_Periodo, Nombre_Convocatoria, Descripcion,
    Cupo_Total, Cupo_Reservado, Cupo_Asignado, Fecha_Inicio, Fecha_Publicacion,
    Fecha_Fin, Fecha_Cierre, Requiere_Postulacion_Linea, Documentacion_Obligatoria,
    Url_Convocatoria, Observaciones, Id_Estado, Id_Estado_Publicacion, Id_Creador,
    Id_Modificador, Id_Usuario_Publicador, Id_Usuario_Cierre, Id_Transaccion,
    Fecha_Creacion, Fecha_Modificacion
) VALUES
('CONV-2024-MAE-001', 1, 3, 'Convocatoria Maestría Excelencia 2024-III', 'Convocatoria para el tercer cuatrimestre 2024', 10, 2, 0, '2024-09-01', '2024-09-15', '2024-10-15', NULL, 1, 'Carta de motivación, Certificado de notas, Carta de recomendación', 'https://becas.universidad.edu.ni/maestria-excelencia', 'Convocatoria abierta', 1, 5, 1, 1, 1, NULL, NULL, GETDATE(), GETDATE()),
('CONV-2024-POS-001', 2, 3, 'Convocatoria Posgrado Investigación 2024-III', 'Convocatoria para estudiantes de posgrado', 5, 1, 0, '2024-09-01', '2024-09-20', '2024-10-20', NULL, 1, 'Proyecto de investigación, CV académico', 'https://becas.universidad.edu.ni/posgrado-investigacion', 'Convocatoria abierta', 1, 5, 1, 1, 1, NULL, NULL, GETDATE(), GETDATE());

-- ============================================================
-- SOLICITUDES DE BECAS
-- ============================================================
INSERT INTO tbl_solicitudes_becas (
    Codigo_Seguimiento, Id_Beca_Programa, Id_Convocatoria, Id_Estudiante,
    Promedio_Vigente, Creditos_Aprobados, Total_Sanciones_Activas, Cumple_Criterios,
    Nivel_Aprobacion_Actual, Nivel_Aprobacion_Maximo, Id_Usuario_Responsable,
    Id_Usuario_Supervisor, Id_Tipo_Decision, Id_Estado, Id_Estado_Flujo,
    Fecha_Solicitud, Fecha_Ultima_Decision, Fecha_Cierre, Motivo_Ultima_Decision,
    Observaciones, Es_Prioritaria, Fecha_Creacion, Fecha_Modificacion,
    Id_Creador, Id_Modificador, Id_Transaccion
) VALUES
('SOL-BEC-000001', 1, 1, 4, 92.50, 125, 0, 1, 1, 3, 7, NULL, 23, 1, 3, '2024-09-16', NULL, NULL, NULL, 'Estudiante con excelente promedio', 0, GETDATE(), GETDATE(), 4, 4, NULL),
('SOL-BEC-000002', 1, 1, 5, 95.00, 130, 0, 1, 2, 3, 7, NULL, 23, 1, 4, '2024-09-17', '2024-09-20', NULL, 'Cumple con todos los criterios', 'Aprobada en primer nivel', 1, GETDATE(), GETDATE(), 5, 7, NULL),
('SOL-BEC-000003', 2, 2, 4, 88.00, 110, 0, 1, 1, 2, 7, NULL, NULL, 1, 3, '2024-09-18', NULL, NULL, NULL, 'Estudiante con proyecto de investigación', 0, GETDATE(), GETDATE(), 4, 4, NULL);




-- ============================================================
-- ROLES DEL SISTEMA
-- ============================================================
-- Nota: El rol ADMINISTRADOR (Id_Rol = 1) ya debe existir en la base de datos
-- Si no existe, descomentar la siguiente línea:
-- INSERT INTO cls_roles (Nombre_Rol, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo) 
-- VALUES ('ADMINISTRADOR', GETDATE(), GETDATE(), NULL, NULL, NULL, 1);

-- Insertar los roles restantes del sistema
INSERT INTO cls_roles (Nombre_Rol, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo) VALUES
('ESTUDIANTE', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),                    -- Id_Rol = 2
('DOCENTE', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),                       -- Id_Rol = 3
('COORDINADOR ACADÉMICO', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),         -- Id_Rol = 4
('COORDINADOR DE BECAS', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),          -- Id_Rol = 5
('SECRETARÍA ACADÉMICA', GETDATE(), GETDATE(), NULL, NULL, NULL, 1);          -- Id_Rol = 6



-- ============================================================
-- MENÚS DEL SISTEMA
-- ============================================================
INSERT INTO cls_menus (Menu, Nombre_Boton, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo) VALUES
('Usuarios', 'btn_UsuarioMenu', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),                    -- Id_Menu = 1
('Estudiantes', 'btn_EstudiantesMenu', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),            -- Id_Menu = 2
('Docentes', 'btn_DocentesMenu', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),                  -- Id_Menu = 3
('Materias', 'btn_MateriasMenu', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),                  -- Id_Menu = 4
('Períodos Académicos', 'btn_PeriodosMenu', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),       -- Id_Menu = 5
('Secciones', 'btn_SeccionesMenu', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),                -- Id_Menu = 6
('Grupos', 'btn_GruposMenu', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),                      -- Id_Menu = 7
('Inscripciones', 'btn_InscripcionesMenu', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),         -- Id_Menu = 8
('Evaluaciones', 'btn_EvaluacionesMenu', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),          -- Id_Menu = 9
('Becas', 'btn_BecasMenu', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),                        -- Id_Menu = 10
('Sanciones Académicas', 'btn_SancionesMenu', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),     -- Id_Menu = 11
('Reportes', 'btn_ReportesMenu', GETDATE(), GETDATE(), NULL, NULL, NULL, 1),                  -- Id_Menu = 12
('Programas de Becas', 'btn_ProgramasBecasMenu', GETDATE(), GETDATE(), NULL, NULL, NULL, 1), -- Id_Menu = 13
('Solicitudes de Becas', 'btn_SolicitudesBecasMenu', GETDATE(), GETDATE(), NULL, NULL, NULL, 1); -- Id_Menu = 14

-- ============================================================
-- RELACIONES MENÚS-ROLES
-- ============================================================
-- ADMINISTRADOR (Id_Rol = 1): Acceso a todos los menús
INSERT INTO cls_menus_roles (Id_Menu, Id_Rol, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo) VALUES
(1, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Usuarios
(2, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Estudiantes
(3, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Docentes
(4, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Materias
(5, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Períodos Académicos
(6, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Secciones
(7, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Grupos
(8, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Inscripciones
(9, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Evaluaciones
(10, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),  -- Becas
(11, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),  -- Sanciones Académicas
(12, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1);  -- Reportes

-- ESTUDIANTE (Id_Rol = 2): Acceso a evaluaciones, becas (solicitudes), inscripciones propias
INSERT INTO cls_menus_roles (Id_Menu, Id_Rol, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo) VALUES
(8, 2, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Inscripciones (propias)
(9, 2, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Evaluaciones (propias)
(10, 2, GETDATE(), GETDATE(), NULL, NULL, NULL, 1);  -- Becas (solicitudes propias)

-- DOCENTE (Id_Rol = 3): Acceso a evaluaciones, secciones propias, grupos propios
INSERT INTO cls_menus_roles (Id_Menu, Id_Rol, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo) VALUES
(6, 3, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Secciones (propias)
(7, 3, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Grupos (propios)
(9, 3, GETDATE(), GETDATE(), NULL, NULL, NULL, 1);  -- Evaluaciones (de sus secciones)

-- COORDINADOR ACADÉMICO (Id_Rol = 4): Acceso a materias, períodos, secciones, grupos, inscripciones, evaluaciones
INSERT INTO cls_menus_roles (Id_Menu, Id_Rol, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo) VALUES
(4, 4, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Materias
(5, 4, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Períodos Académicos
(6, 4, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Secciones
(7, 4, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Grupos
(8, 4, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Inscripciones
(9, 4, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),  -- Evaluaciones
(12, 4, GETDATE(), GETDATE(), NULL, NULL, NULL, 1); -- Reportes

-- COORDINADOR DE BECAS (Id_Rol = 5): Acceso a becas (programas, convocatorias, solicitudes)
INSERT INTO cls_menus_roles (Id_Menu, Id_Rol, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo) VALUES
(10, 5, GETDATE(), GETDATE(), NULL, NULL, NULL, 1), -- Becas
(12, 5, GETDATE(), GETDATE(), NULL, NULL, NULL, 1); -- Reportes

-- SECRETARÍA ACADÉMICA (Id_Rol = 6): Acceso a estudiantes, inscripciones, sanciones, períodos
INSERT INTO cls_menus_roles (Id_Menu, Id_Rol, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo) VALUES
(2, 6, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Estudiantes
(5, 6, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Períodos Académicos
(8, 6, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),   -- Inscripciones
(11, 6, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),  -- Sanciones Académicas
(12, 6, GETDATE(), GETDATE(), NULL, NULL, NULL, 1);  -- Reportes

-- ADMINISTRADOR (Id_Rol = 1): Acceso a menús adicionales (Programas de Becas y Solicitudes de Becas)
INSERT INTO cls_menus_roles (Id_Menu, Id_Rol, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo) VALUES
(13, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),  -- Programas de Becas
(14, 1, GETDATE(), GETDATE(), NULL, NULL, NULL, 1);  -- Solicitudes de Becas

-- ESTUDIANTE (Id_Rol = 2): Acceso a Solicitudes de Becas (propias)
INSERT INTO cls_menus_roles (Id_Menu, Id_Rol, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo) VALUES
(14, 2, GETDATE(), GETDATE(), NULL, NULL, NULL, 1);  -- Solicitudes de Becas (propias)

-- COORDINADOR DE BECAS (Id_Rol = 5): Acceso a Programas de Becas y Solicitudes de Becas
INSERT INTO cls_menus_roles (Id_Menu, Id_Rol, Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion, Activo) VALUES
(13, 5, GETDATE(), GETDATE(), NULL, NULL, NULL, 1),  -- Programas de Becas
(14, 5, GETDATE(), GETDATE(), NULL, NULL, NULL, 1);  -- Solicitudes de Becas

-- ============================================================
-- MODELOS DE EVALUACIONES
-- ============================================================
INSERT INTO cls_evaluaciones_modelos (
    Id_Materia_Periodo, Id_Tipo_Evaluacion, Codigo_Modelo, Nombre_Evaluacion,
    Concepto, Calificacion_Maxima, Peso_Porcentual, Orden, Requiere_Aprobacion,
    Version_Configuracion, Id_Metodo_Calculo, Rubrica_Detalle, Porcentaje_Minimo_Aprobacion,
    Niveles_Revision, Id_Rol_Aprobador, Permite_Recalculo, Tiempo_Maximo_Carga,
    Fecha_Inicio, Fecha_Fin, Fecha_Creacion, Fecha_Modificacion, Id_Creador,
    Id_Modificador, Id_Transaccion, Activo
) VALUES
-- Modelos para PROG-201 (Id_Materia_Periodo = 2)
(2, 28, 'MOD-PROG-201-001', 'Examen Parcial I', 'Evaluación de conceptos básicos de programación', 100.00, 30.00, 1, 1, 1, 21, NULL, 60.00, 2, 5, 0, NULL, '2024-10-01', '2024-10-15', GETDATE(), GETDATE(), 2, 2, NULL, 1),
(2, 28, 'MOD-PROG-201-002', 'Examen Parcial II', 'Evaluación de programación orientada a objetos', 100.00, 30.00, 2, 1, 1, 21, NULL, 60.00, 2, 5, 0, NULL, '2024-11-01', '2024-11-15', GETDATE(), GETDATE(), 2, 2, NULL, 1),
(2, 30, 'MOD-PROG-201-003', 'Proyecto Final', 'Desarrollo de aplicación completa', 100.00, 40.00, 3, 1, 1, 21, NULL, 70.00, 3, 5, 1, NULL, '2024-11-20', '2024-12-10', GETDATE(), GETDATE(), 2, 2, NULL, 1),
-- Modelos para BD-301 (Id_Materia_Periodo = 4)
(4, 28, 'MOD-BD-301-001', 'Examen Parcial', 'Diseño de bases de datos', 100.00, 35.00, 1, 1, 1, 21, NULL, 65.00, 2, 5, 0, NULL, '2024-10-10', '2024-10-25', GETDATE(), GETDATE(), 3, 3, NULL, 1),
(4, 30, 'MOD-BD-301-002', 'Proyecto Base de Datos', 'Implementación de sistema completo', 100.00, 65.00, 2, 1, 1, 21, NULL, 70.00, 3, 5, 1, NULL, '2024-11-01', '2024-12-01', GETDATE(), GETDATE(), 3, 3, NULL, 1);

-- ============================================================
-- INSTANCIAS DE EVALUACIONES
-- ============================================================
INSERT INTO tbl_evaluaciones_instancias (
    Codigo_Instancia, Id_Seccion, Id_Evaluacion_Modelo, Id_Periodo, Fecha_Programada,
    Fecha_Limite, Requiere_Revision_Interna, Numero_Version, Nivel_Aprobacion_Actual,
    Id_Estado, Id_Estado_Publicacion, Id_Responsable_Revision, Fecha_Revision,
    Id_Responsable_Publicacion, Fecha_Publicacion, Id_Evaluacion_Padre,
    Observaciones_Revision, Motivo_Rechazo, Fecha_Creacion, Fecha_Modificacion,
    Id_Creador, Id_Modificador, Id_Transaccion
) VALUES
-- Instancias para PROG-201-A (Id_Seccion = 2)
('INST-PROG-201-A-001', 2, 1, 3, '2024-10-05 08:00:00', '2024-10-05 10:00:00', 1, 1, 2, 1, 5, 3, '2024-10-04', 2, '2024-10-04', NULL, 'Aprobada para publicación', NULL, GETDATE(), GETDATE(), 2, 2, NULL),
('INST-PROG-201-A-002', 2, 2, 3, '2024-11-05 08:00:00', '2024-11-05 10:00:00', 1, 1, 1, 1, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), GETDATE(), 2, 2, NULL),
-- Instancias para BD-301-A (Id_Seccion = 5)
('INST-BD-301-A-001', 5, 4, 3, '2024-10-15 08:00:00', '2024-10-15 11:00:00', 1, 1, 2, 1, 5, 3, '2024-10-14', 3, '2024-10-14', NULL, 'Evaluación lista', NULL, GETDATE(), GETDATE(), 3, 3, NULL);

-- ============================================================
-- EVALUACIONES DE ALUMNOS
-- ============================================================
INSERT INTO tbl_evaluaciones_alumnos (
    Codigo_Registro, Id_Evaluacion_Instancia, Id_Inscripcion, Puntaje_Obtenido,
    Porcentaje_Logrado, Puntaje_Normalizado, Es_Recalculo, Numero_Recalculo,
    Motivo_Ajuste, Observaciones, Id_Usuario_Evaluador, Id_Usuario_Validador,
    Fecha_Validacion, Id_Estado, Id_Estado_Publicacion, Id_Evaluacion_Reemplazada,
    Firmado_Por_Estudiante, Firma_Digital, Fecha_Notificacion, Fecha_Publicacion,
    Fecha_Creacion, Fecha_Modificacion, Id_Creador, Id_Modificador, Id_Transaccion
) VALUES
-- Evaluaciones para estudiante 4 (Id_Inscripcion = 4) en PROG-201-A
('EVAL-2024-001', 1, 4, 85.00, 85.00, 0.8500, 0, 0, NULL, 'Buen desempeño', 2, 3, '2024-10-06', 1, 5, NULL, 1, 'FIRMA-DIG-001', '2024-10-06', '2024-10-06', GETDATE(), GETDATE(), 2, 2, NULL),
-- Evaluaciones para estudiante 5 (Id_Inscripcion = 5) en PROG-201-A
('EVAL-2024-002', 1, 5, 95.00, 95.00, 0.9500, 0, 0, NULL, 'Excelente trabajo', 2, 3, '2024-10-06', 1, 5, NULL, 1, 'FIRMA-DIG-002', '2024-10-06', '2024-10-06', GETDATE(), GETDATE(), 2, 2, NULL),
-- Evaluaciones para estudiante 9 (Id_Inscripcion = 6) en PROG-201-A
('EVAL-2024-003', 1, 6, 72.00, 72.00, 0.7200, 0, 0, NULL, 'Necesita mejorar', 2, 3, '2024-10-06', 1, 5, NULL, 0, NULL, '2024-10-06', '2024-10-06', GETDATE(), GETDATE(), 2, 2, NULL),
-- Evaluaciones para estudiante 4 (Id_Inscripcion = 11) en BD-301-A
('EVAL-2024-004', 3, 11, 88.00, 88.00, 0.8800, 0, 0, NULL, 'Buen diseño de BD', 3, 3, '2024-10-16', 1, 5, NULL, 1, 'FIRMA-DIG-003', '2024-10-16', '2024-10-16', GETDATE(), GETDATE(), 3, 3, NULL);

-- ============================================================
-- HISTORIAL DE SOLICITUDES DE BECAS
-- ============================================================
INSERT INTO tbl_solicitudes_becas_historial (
    Id_Solicitud_Beca, Id_Estado_Anterior, Id_Estado_Nuevo, Id_Usuario_Revisor,
    Fecha_Decision, Motivo_Decision, Observaciones
) VALUES
(2, 3, 4, 7, '2024-09-20', 'Cumple con todos los criterios establecidos', 'Estudiante con excelente promedio y sin sanciones');
